# Dataset


Summary of India COVID-19


In [83]:
import numpy as np
data = np.loadtxt('summary_india.txt')
data

array([[ 904.,  548.,   24.,   30.],
       [1004., 1035.,  139.,   40.],
       [1104.,  909.,   73.,   34.],
       [1204.,  796.,  141.,   35.],
       [1304., 1211.,  179.,   31.],
       [1404., 1076.,  270.,   38.],
       [1504.,  941.,  183.,   37.],
       [1604., 1007.,  260.,   23.],
       [1704.,  991.,  243.,   43.],
       [1804., 1334.,  239.,   27.],
       [1904., 1553.,  316.,   36.],
       [2004.,  391.,  295.,   16.],
       [2104.,  945.,  410.,   31.],
       [2204., 1383.,  618.,   50.],
       [2304., 1409.,  388.,   41.],
       [2404., 3113.,  805.,   94.],
       [2504., 1990.,  741.,   49.],
       [2604., 1396.,  381.,   48.]])

In [84]:
Date,Confrm,Recov,Death = data.T #columns to variables
Date

array([ 904., 1004., 1104., 1204., 1304., 1404., 1504., 1604., 1704.,
       1804., 1904., 2004., 2104., 2204., 2304., 2404., 2504., 2604.])

In [86]:
#The mean population over time
Data = data[1:, :]
Data

array([[1004., 1035.,  139.,   40.],
       [1104.,  909.,   73.,   34.],
       [1204.,  796.,  141.,   35.],
       [1304., 1211.,  179.,   31.],
       [1404., 1076.,  270.,   38.],
       [1504.,  941.,  183.,   37.],
       [1604., 1007.,  260.,   23.],
       [1704.,  991.,  243.,   43.],
       [1804., 1334.,  239.,   27.],
       [1904., 1553.,  316.,   36.],
       [2004.,  391.,  295.,   16.],
       [2104.,  945.,  410.,   31.],
       [2204., 1383.,  618.,   50.],
       [2304., 1409.,  388.,   41.],
       [2404., 3113.,  805.,   94.],
       [2504., 1990.,  741.,   49.],
       [2604., 1396.,  381.,   48.]])

In [105]:
#On which date has the highest confirmed?

np.argmax(covid_sum[:, 1:], axis=1)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [23]:
covid_sum.std(axis=0)

array([582.85137762, 209.34487023,  15.88315747])

# Sorting

In [106]:
x = np.array([[5, 4, 6], [2, 3, 2]])
y = np.sort(x, axis=1)
y

array([[4, 5, 6],
       [2, 2, 3]])

In [107]:
x.sort(axis=1)
x

array([[4, 5, 6],
       [2, 2, 3]])

In [80]:
z = np.array([5, 6, 3, 7])
j = np.argsort(z)
j

array([2, 0, 1, 3], dtype=int32)

In [81]:
z[j]

array([3, 5, 6, 7])

BROADCASTING


In [109]:
arr1 = np.tile(np.arange(40, 80, 10), (3,1))
arr1

array([[40, 50, 60, 70],
       [40, 50, 60, 70],
       [40, 50, 60, 70]])

In [50]:
arr1=arr1.T
arr1

array([[40, 40, 40],
       [50, 50, 50],
       [60, 60, 60],
       [70, 70, 70]])

In [29]:
arr2 = np.array([10, 20, 30])
arr1 + arr2

array([[ 50,  60,  70],
       [ 60,  70,  80],
       [ 70,  80,  90],
       [ 80,  90, 100]])

In [45]:
arr3 = np.arange(0, 40, 10)
arr3.shape

(4,)

In [110]:
arr3 = arr3[:, np.newaxis]  # adds a new axis to convert into 2D array
arr3

array([[ 0],
       [10],
       [20],
       [30]])

# Basic Functions On Numpy

In [58]:
x = np.array([[100, 300, 500], [200, 400, 600]])
x.ravel()

array([100, 300, 500, 200, 400, 600])

In [60]:
x.T.ravel()

array([100, 200, 300, 400, 500, 600])

In [65]:
z = np.array([[100, 500, 1500], [1200, 1400, 1600]])
z.shape

(2, 3)

In [112]:
z.ravel()

array([5, 6, 3, 7])

Resizing

In [73]:
y=np.arange(3)
y.resize((6,))
y

array([0, 1, 2, 0, 0, 0])

# Referencing here , will not work

In [74]:
z=y
z.resize((8,0))
z

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False